// package vu.psk.ugems.mapper;
//
// import java.util.List;
//
// import org.mapstruct.Mapper;
// import org.mapstruct.Mapping;
//
// import vu.psk.ugems.dto.InvitationDTO;
// import vu.psk.ugems.entity.Invitation;
//
// @Mapper(componentModel = "spring")
// public interface InvitationMapper {
//
//     @Mapping(target = "id", ignore = true) // id generated by DB
//     @Mapping(target = "inviteeEmail", ignore = true)
//     @Mapping(target = "inviteStatus", constant = "PENDING")
//     @Mapping(target = "group", ignore = true)     // set manually in service
//     @Mapping(target = "invitedBy", ignore = true) // set manually in service
//     @Mapping(target = "recipientId", ignore = true) // set manually or remove if you use email only
//     Invitation toEntity(InvitationDTO dto);
//
//     @Mapping(source = "id", target = "id")
//     @Mapping(source = "email", target = "inviteeEmail")
//     @Mapping(source = "group.id", target = "groupId")
//     @Mapping(source = "invitedBy.id", target = "inviterId")
//     InvitationDTO toDto(Invitation invitation);
//
//     List<InvitationDTO> toDtoList(List<Invitation> invitations);
// }